site_name: Cosckoya's Cheatsheets
site_url: https://cosckoya.github.io/wiki
site_description: Cosckoya's Tech Wiki
site_author: 'cosckoya'

repo_url: https://github.com/cosckoya/wiki
edit_uri: ""

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - zsh
    - yaml
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

nav:
  - Home: index.md
  - About: about.md
