site_name: Cosckoya's Cheatsheets
site_url: https://cosckoya.github.io/wiki
site_description: Cosckoya's Tech Wiki
site_author: 'cosckoya'

repo_url: https://github.com/cosckoya/wiki
edit_uri: ""

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  language: en
  highlightjs: true
  hljs_languages:
    - zsh
    - yaml
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

nav:
  - Home: 'index.md'
  - Code:
    - Shell: 'code/shell.md'
    - Python: 'code/python.md'
  - Linux:
    - Shell: 'linux/shell.md'
    - Network: 'linux/network.md'
    - Storage: 'linux/storage.md'
    - Tools: 'linux/tools.md'
  - Databases:
    - SQL: 'databases/sql.md'
    - NoSQL: 'databases/nosql.md'
  - Cloud:
    - AWS: 'cloud/aws.md'
    - Azure: 'cloud/azure.md'
    - Google: 'cloud/google.md'
  - Containers:
    - Docker: 'container/docker.md'
    - Kubernetes: 'container/kubernetes.md'
  - Security: 'security/index.md'
  - DevOps:
    - Jenkins: 'devops/jenkins.md'
    - 'Github Actions': 'devops/gh-actions.md'
    - 'Azure DevOps': 'devops/azure-ops.md'
  - Monitoring:
    - Zabbix: 'monitoring/zabbix.md'
    - Influxdb: 'monitoring/influxdb.md'
    - Prometheus: 'monitoring/prometheus.md'
  - Bookmarks: 'bookmarks.md'
  - About: 'about.md'
