site_name: Wiki
site_url: https://cosckoya.github.io/wiki
site_description: Cosckoya's Tech Wiki
site_author: 'cosckoya'

repo_url: https://github.com/cosckoya/wiki
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - zsh
        - yaml

nav:
    - Home: index.md
